# @package _global_
hydra:
  launcher:
    partition: gpu_normal
    gres: gpu:1
    mem_gb: 16
    cpus_per_task: 6
    timeout_min: 1440 # 24h
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
